# Generated by Django 4.2.6 on 2024-06-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_duration',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
