# Generated by Django 4.2.6 on 2024-06-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='title',
        ),
    ]
